config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, {class_name: 'User'}.merge(ActiveAdmin::Devise.config)
  ActiveAdmin.routes(self)

  devise_for :users
  # resources :users


  resources :class_videos do
    resources :comments, only: [:create]
  end
  resources :topics do
    resources :comments, only: [:create]
  end

  # 个人主页
  get '~:nickname', to: "users#topics", as: :user_activity
  get '~:nickname/topics', to: "users#topics", as: :user_topics
  get '~:nickname/comments', to: "users#comments", as: :user_comments
  # 编辑个人信息
  get 'settings/account', to: "users#account"
  get 'settings/password', to: "users#password"
  get 'settings/profile', to: "users#profile"
  get 'settings/notifications', to: "users#notifications"
  patch 'settings/update_user', to: "users#update_user"



  root 'class_videos#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    user ||= User.new

    # 其实下面的这种默认写法，不支持一个人有多个角色的情况
    # if user.has_role? :video_admin
    #   can :manage, ClassVideo
    #   # can :read, Topic
    # elsif user.has_role? :community_admin
    #   can :manage, Topic
    #   can :manage, Comment
    # else
    #   can :read, :all
    # end
    if user.has_role? :video_admin
      can :manage, ClassVideo
    else
      can :read, :all
    end

    if user.has_role? :community_admin
      can :manage, Topic
      can :manage, Comment
    end
  end
end

app/models/class_video.rb
class ClassVideo < ActiveRecord::Base
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  belongs_to :user, foreign_key: :user_id

  validates_presence_of :content
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user, foreign_key: :user_id

  validates_presence_of :title, message: '标题不能为空'
  validates_presence_of :content, message: '话题内容不能为空'

  # paginates_per 1
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments, dependent: :destroy
  has_many :topics, dependent: :destroy

  SETTINGS = ['account', 'password', 'profile', 'notifications']

  # 以下这三个方法，就把角色定义清楚了。user.roles是个array。
  # 设计非常巧妙，根本不需要知道roles_mask哪个数字对应什么，只需要知道有没有这个角色，且mask数字不重复即可
  ROLES = [:video_admin, :community_admin]

  def roles=(roles)
   roles = [*roles].map { |r| r.to_sym }
   self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.inject(0, :+) # 3**2 == 9, **是幂。array#&，取两者重合
  end

  def roles
   ROLES.reject do |r|
     ((roles_mask.to_i || 0) & 2**ROLES.index(r)).zero? # 3 & 2 => 2, 0 & 2 => 0
   end
  end

  def has_role?(role)
   roles.include?(role)
  end

  def to_s
    nickname
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)  { |u| u.permit(:email,:password, :password_confirmation, :nickname, roles: []) }
  end
end

app/controllers/class_videos_controller.rb
class ClassVideosController < ApplicationController
  before_action :find_video, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @class_videos = ClassVideo.all.order('created_at ASC')
  end

  def show
    @commentable = ClassVideo.find(params[:id])
    @comments = @commentable.comments
    # @class_video = ClassVideo.includes(:comments).find(params[:id])
    # @comments = @class_video.comments
  end

  def new
    @class_video = ClassVideo.new
  end

  def create
    @class_video = ClassVideo.new video_params

    if @class_video.save!
      redirect_to @class_video, notice: "Successfully create new class_videos"
    else
      render 'new'
    end
  end

  def edit
    #code
  end

  def update
    if @class_video.update(video_params)
      redirect_to @class_video
    else
      render 'edit' # render 带参数，所以回来的时候，之前填写的数据不会丢失
    end
  end

  def destroy
    @class_video.destroy
    redirect_to root_path, notice: "Successfully delete the class video"
  end

  private

  def video_params
    params[:class_video].permit(:title, :speakers, :cover_image, :play_count, :video, :description)
  end

  def find_video
    @class_video = ClassVideo.find(params[:id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :find_commentable
  before_action :authenticate_user!
  load_and_authorize_resource

  def create
   @comment = @commentable.comments.build(comment_params.merge(user: current_user))
   @comment.save!
   @comments = @commentable.comments
   respond_to do |format|
     format.html {redirect_to @commentable}
     format.js
   end
  end

  private

  def find_commentable
   c_id = params[:class_video_id]
   t_id = params[:topic_id]
   @commentable = if c_id.present?
                    ClassVideo.find(c_id)
                  else t_id.present?
                    Topic.find(t_id)
                  end
  end

  def comment_params
   params[:comment].permit(:content)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :find_topic, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  load_and_authorize_resource

  def index
    @topics = Topic.order('created_at DESC').page params[:page]
    # logger.info params
  end

  def show
    @commentable = Topic.find(params[:id])
    @comments = @commentable.comments
  end

  def new
    @topic = current_user.topics.build
  end

  def create
    @topic = current_user.topics.build topic_params
    if @topic.save
      redirect_to @topic, notice: "Successfully create new topics"
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @topic.update topic_params
      redirect_to @topic, notice: "Successfully update topic"
    else
      render 'edit'
    end
  end

  def destroy
    @topic.destroy
    redirect_to topics_path, notice: "Successfully delete the topic"
  end

  private
  def topic_params
    params[:topic].permit(:title, :content)
  end

  def find_topic
    @topic = Topic.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:comments, :topics]
  before_action :authenticate_user!, except: [:comments, :topics]

  def topics
    @content = @user.topics
  end

  def comments
    @content = @user.comments
  end

  def account
    @user = current_user
    #code
  end

  def password
    @user = current_user
    #code
  end

  def profile
    #code
  end

  def notifications
    #code
  end

  def update_user
    @user = current_user
    pp user_params
    @user.update user_params
    # sign_in @user, :bypass => true
    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def find_user
    @user = User.find_by_nickname(params[:nickname])
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :avartar, :current_password, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/class_videos_helper.rb
module ClassVideosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/class_videos/_form.html.erb
<%= simple_form_for @class_video do |f| %>
  <%= f.input :title %>
  <%= f.input :speakers %>
  <%= f.input :cover_image %>
  <%= f.input :play_count %>
  <%= f.input :video %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/class_videos/edit.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1>Edit Video</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/class_videos/index.html.erb
<div class="list-group">
  <% @class_videos.find_each do |video| %>
    <div class="class-video">
      <%= link_to "/class_videos/#{video.id}", style:"text-decoration:none;" do %>
        <div class="video-img">
          <%= image_tag video.cover_image %>
        </div>
        <div class="class-info">
          <div class="class-title">
            <%= video.title %>
          </div>
          <div class="class-speakers">
            <%= video.speakers %>
          </div>
          <div class="counts">
            <div class="play-count">
              <%= video.play_count.presence || '12.5K' %>
            </div>
            <div class="play-text">
              观看
            </div>
          </div>
          <div class="subtitle">
            中文字幕
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/class_videos/new.html.erb
<h1>New Video</h1>

<%= render 'form' %>  

app/views/class_videos/show.html.erb
<div class="video_area">
  <video id="my-video" class="video-js" controls preload="auto" data-setup="{}"  >
    <source src= <%= @class_video.video %> type='video/mp4'>
    <p class="vjs-no-js">
      To view this video please enable JavaScript, and consider upgrading to a web browser that
      <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
    </p>
  </video>
</div>


<h3 class="yc-video-title">
  <%= @class_video.title %>
</h3>
<div class="yc-video-info">
  <div class="panel" id="note">
    <div class="panel-heading">
      <h3 class="panel-title">课程资料</h3>
    </div>
    <div class="panel-body">
      <%= @class_video.description %>
    </div>
  </div>
  <%= render 'comments/index' %>
  <%= render 'comments/form' %>
</div>

<!-- cancancan checking_ability 示例 -->
<% if can? [:edit, :destroy], @class_video %>
  <%= link_to "edit", edit_class_video_path, class: "btn btn-default" %>
  <%= link_to "delete", class_video_path, method: :delete, data:{confirm: 'Are you sure?'}, class: "btn btn-default" %>
<% end %>

app/views/comments/_comment.html.erb
<div class="comment group-item last-child" id="comment-<%= comment.id %>">
  <div class="comment-avatar">

  </div>
  <div class="comment-content">
    <div class="comment-heading">
      <b><%= comment.user.nickname %></b>
      <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
    </div>
    <div class="comment-body">
      <%= comment.content %>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="panel">
  <% if user_signed_in? %>
    <div class="panel-body">
      <div class="comment">
        <div class="comment-avatar">

        </div>
        <div class="comment-content">
          <div class="comment-heading">
            <b><%= current_user.nickname %></b>
          </div>
          <div class="comment-body">
            <% comment = @commentable.comments.build %>
            <%= simple_form_for [@commentable, comment], remote: true do |f|%>
              <%= f.input :content, label: false, as: :text %>
              <%= f.button :submit, class: "btn btn-success" %>
              <!-- TODO play with simple_form, like hint and warning-->
            <% end %>

          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="panel-body">
      <%= link_to "注册", new_user_registration_path %> 或
      <%= link_to "登录", new_user_session_path %> 后发表评论
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<div class="panel" id="comments">
  <div class="panel-heading">
    <h3 class="panel-title">
      评论(<%= @comments.count %>)
    </h3>
  </div>
  <div class="panel-body" style="padding-bottom: 0;">
    <div class="list-group comments">
      <% @comments.find_each do |comment| %>
        <% max_id = @comments.collect {|c| c.id}.max %>
        <% unless comment.id == max_id %>
          <div class="comment list-group-item" id="comment-<%= comment.id %>">
        <% else %>
          <div class="comment list-group-item last-child" id="comment-<%= comment.id %>">
        <% end %>
            <div class="comment-avatar">

            </div>
            <div class="comment-content">
              <div class="comment-heading">
                <b><%= comment.user.nickname %></b>
                <%= comment.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
              </div>
              <div class="comment-body">
                <%= comment.content %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/comments/_new.html.erb
<div class="panel">
  <% if user_signed_in? %>
    <div class="panel-body">
      <div class="comment">
        <div class="comment-avatar">

        </div>
        <div class="comment-content">
          <div class="comment-heading">
            <b><%= current_user.email %></b>
          </div>
          <div class="comment-body">
            <%= simple_form_for @comment do |f|%>
              <%= f.input :content, as: :text %>
              <%= f.button :submit %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="panel-body">
      <%= link_to "注册", new_user_registration_path %> 或
      <%= link_to "登录", new_user_session_path %> 后发表评论
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
<% if @comment.errors.empty? %>
  $('.last-child').removeClass('last-child')
  new_comment = "<%= j render 'comment', comment: @comment %>";
  $('.comments').append(new_comment);
  animated();
<% else %>
  $('#comment-errors').html("<%= j render 'shared/error_messages', object: @comment %>");
  $('#error_explanation').addClass('animated shake');
<% end %>

function animated() {
  $('#comment-<%= @comment.id %>').addClass('animated bounceIn');
  $('textarea').val("");
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StartupClass</title>
  <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "YC Startup Class", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <% if params[:controller] == 'class_videos' %>
            <li class="active"><%= link_to "课程视频", root_path %></li>
            <li><%= link_to "社区", topics_path %></li>
          <% elsif params[:controller] == 'topics' %>
            <li><%= link_to "课程视频", root_path %></li>
            <li class="active"><%= link_to "社区", topics_path %></li>
          <% else %>
            <li><%= link_to "课程视频", root_path %></li>
            <li><%= link_to "社区", topics_path %></li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <%= current_user.nickname %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "个人页面", user_activity_path(current_user.nickname) %></li>
                <li><%= link_to "设置", settings_account_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "退出", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "注册", new_user_registration_path %></li>
            <li><%= link_to "登录", new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </div><!-- container-fluid -->
  </div><!-- navbar navbar-default -->
  <link href="http://vjs.zencdn.net/5.8.7/video-js.css" rel="stylesheet">
  <script src="http://vjs.zencdn.net/5.8.7/video.js"></script>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class:"alert" %>
    <% end %>
    <div class="row">
      <% if params[:controller] == 'class_videos' || params[:controller] == 'topics' %>
        <div class="col-md-10 col-md-push-1">
          <%= yield %>
        </div>
      <% else %>
        <%= yield %>
      <% end %>
    </div>
  </div>


</body>
</html>

app/views/topics/_form.html.erb
<%= simple_form_for @topic do |f| %>
  <%= f.input :title%>
  <%= f.input :content, as: :text%>
  <%= f.button :submit, class: "btn btn-success" %>
<% end %>

app/views/topics/edit.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1>Edit Topic</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/index.html.erb
<div class="panel">
  <div class="panel-body">
    <div class="pull-right">
      <div class="input-group">
        <!-- TODO SEARCH -->
      </div>
    </div>
    <%= link_to "创建话题", new_topic_path, class: "btn btn-success" %>
  </div>
</div>
<div class="panel">
  <div class="panel-body" id="topic-lists">
    <div class="list-group">
      <% @topics.find_each do |topic| %>
        <% max_id = @topics.collect {|t| t.id}.max %>
        <% unless topic.id == max_id %>
          <a class="list-group-item topic" href="<%= "/topics/#{topic.id}" %>">
            <div class="topic-heading">
              <%= topic.title %>
            </div>
            <div class="topic-info text-muted">
              <%= topic.user.nickname %> ·
              <%= topic.created_at.strftime("%Y-%m-%d %H:%M:%S") %> ·
              <%= topic.comments.count %>条评论
            </div>
          </a>
        <% else %>
          <a class="last-child list-group-item topic" href="<%= "/topics/#{topic.id}" %>">
            <div class="topic-heading">
              <%= topic.title %>
            </div>
            <div class="topic-info text-muted">
              <%= topic.user.nickname %> ·
              <%= topic.created_at.strftime("%Y-%m-%d %H:%M:%S") %> ·
              <%= topic.comments.count %>条评论
            </div>
          </a>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="panel-footer">
    <div class="pull-right">
      <%= paginate @topics %>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="panel">
  <div class="panel-heading">
    <h1>New Topic</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/topics/show.html.erb
<div class="panel">
  <div class="panel-heading">
    <h3><%= @topic.title %></h3>
  </div>
  <div class="panel-body">
    <div class="list-group">
        <div class="comment">
          <div class="comment-avatar">

          </div>
          <div class="comment-content">
            <div class="comment-heading">
              <b><%= @topic.user.nickname %></b>
              <%= @topic.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
              <!-- TODO timezone wrong -->
            </div>
            <div class="comment-body">
              <%= @topic.content %>
            </div>
          </div>
        </div>
    </div>
  </div>
</div>
<%= render 'comments/index' %>
<%= render 'comments/form' %>

app/views/users/_left.html.erb
<div class="col-md-4">
  <div class="panel user-profile">
    <div class="panel-body">
      <div class="user-profile-avartar">

      </div>
      <div class="user-profile-name">
        <%= @user.nickname %>
      </div>
    </div>
    <div class="panel-footer">
      <% if user_signed_in? && current_user == @user %>
        <%= link_to "编辑个人资料", settings_profile_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
  <div class="list-group" style="margin:0;">
    <% if params[:action] == 'comments' %>
      <%= link_to user_topics_path, class: "list-group-item" do %>
        <div class="pull-right"><i class="fa fa-chevron-right"></i></div>
        Topics
      <% end %>
      <%= link_to user_comments_path, class: "list-group-item active" do %>
        <div class="pull-right"><i class="fa fa-chevron-right"></i></div>
        Comments
      <% end %>
    <% else %>
      <%= link_to user_topics_path, class: "list-group-item active" do %>
        <div class="pull-right"><i class="fa fa-chevron-right"></i></div>
        Topics
      <% end %>
      <%= link_to user_comments_path, class: "list-group-item" do %>
        <div class="pull-right"><i class="fa fa-chevron-right"></i></div>
        Comments
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/_right.html.erb
<div class="col-md-8">
  <div class="panel" id="Topics">
    <div class="panel-heading clearfix">
      <div class="pull-right">
        <ul class="nav nav-pills">
          <li class="active"><%= link_to "发布", '' %></li>
          <li><%= link_to "喜欢", '' %></li>
        </ul>
      </div>
      <h3 class="panel-title"><%= params[:action].upcase %></h3>
    </div>
    <div class="panel-body">
      <div class="list-group">
        <% @content.each do |content| %>
          <%
          # TODO 拼写错误检查
          bundle_type = if params[:action] == 'topics'
                           'topics'
                        elsif content.commentable.class.to_s.downcase == 'topic'
                             'topics'
                        else
                             'class_videos'
                        end
          %>
          <% bundle_id = params[:action] == 'topics'? content.id : content.commentable.id %>
          <a class="list-group-item" href="<%= "/#{bundle_type}/#{bundle_id}" %>">
            <div class="list-group-item-avartar">

            </div>
            <div class="list-group-item-content">
              <div class="list-group-item-heading">
                <% if params[:action] == 'comments' %>
                  <%= content.commentable.title %>
                <% else %>
                  <%= content.title %>
                <% end %>
                <span class="text-muted"> · <%= time_ago_in_words(content.created_at) %> ago</span>
              </div>
              <div class="text-muted">
                <%= content.content %>
              </div>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/_settings.html.erb
<div class="col-md-4">
  <div class="list-group" style="margin:0;">
    <% ::User::SETTINGS.each do |setting| %>
      <% class_spec = params[:action] == setting ? "list-group-item active" : "list-group-item" %>
      <%= link_to "#{setting}", class: "#{class_spec}" do %>
        <div class="pull-right"><i class="fa fa-chevron-right"></i></div>
        <%= setting.capitalize %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/account.html.erb
<%= render 'settings' %>
<%= link_to "Change your password", edit_user_registration_path, class: "btn btn-primary" %>
<div class="col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title"><%= params[:action].capitalize %></h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @user, url: settings_update_user_path, remote: true do |f| %>
        <%= f.input :nickname %>
        <%= f.input :email %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.button :submit, "Save Changes", class: "btn btn-success"  %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/comments.html.erb
<%= render 'left' %>
<%= render 'right' %>

app/views/users/notifications.html.erb
<%= render 'settings' %>

<div class="col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title"><%= params[:action].capitalize %></h3>
    </div>
    <div class="panel-body">

    </div>
  </div>
</div>

app/views/users/password.html.erb
<%= render 'settings' %>

<!-- <div class="col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title"><%= params[:action].capitalize %></h3>
    </div>
    <div class="panel-body">
      <%= simple_form_for @user, url: settings_update_user_path, remote: true do |f| %>
        <%= f.input :current_password %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
        <%= f.button :submit, "Change Password", class: "btn btn-success"  %>
      <% end %>
    </div>
  </div>
</div> -->

app/views/users/profile.html.erb
<%= render 'settings' %>

<div class="col-md-8">
  <div class="panel">
    <div class="panel-heading">
      <h3 class="panel-title"><%= params[:action].capitalize %></h3>
    </div>
    <div class="panel-body">

    </div>
  </div>
</div>

app/views/users/topics.html.erb
<%= render 'left' %>
<%= render 'right' %>